/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shootloking_secretmessager_utility_JniUtils */

#ifndef _Included_com_shootloking_secretmessager_utility_JniUtils
#define _Included_com_shootloking_secretmessager_utility_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shootloking_secretmessager_utility_JniUtils
 * Method:    getAESKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shootloking_secretmessager_utility_JniUtils_getAESKey
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
